apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.org_charts.api.name}}-deployment
  namespace: {{ .Values.org_charts.namespace }}
  labels:
    app.kubernetes.io/name: {{.Values.org_charts.api.name}}-deployment
    app.kubernetes.io/part-of: {{ .Values.org_charts.name }}

spec:
  {{- if not .Values.org_charts.autoscaling.enabled }}
  replicas: {{ .Values.org_charts.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.org_charts.api.name }}-deployment
      app.kubernetes.io/part-of: {{ .Values.org_charts.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.org_charts.api.name }}-deployment
        app.kubernetes.io/part-of: {{ .Values.org_charts.name }}
    spec:
      containers:
        - name: {{ .Values.org_charts.api.name }}
          image: '{{.Values.global.repository_url}}/{{.Values.org_charts.api.image.url}}:{{.Values.org_charts.api.image.tag}}'
          imagePullPolicy: {{.Values.org_charts.api.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.org_charts.api.service.port}}
              protocol: TCP
          env:
            - name: spring.datasource.url
              value: 'jdbc:mysql://{{ .Values.org_charts.database.credentials.hostname }}:3306/{{ .Values.org_charts.database.credentials.database_name }}'
            - name: spring.datasource.username
              value: '{{.Values.org_charts.database.credentials.username }}'
            - name: spring.datasource.password
              value: '{{ .Values.org_charts.database.credentials.password }}'
            - name: spring.jpa.properties.hibernate.dialect
              value: 'org.hibernate.dialect.MySQL5Dialect'
            - name: spring.datasource.initialization-mode
              value: 'always'
            - name: spring.jpa.hibernate.ddl-auto
              value: 'update'