apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.org_charts.pvc.name }}
  namespace: {{ .Values.org_charts.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.org_charts.pvc.storage}}
