apiVersion: v1
kind: Service
metadata:
  name: {{.Values.org_charts.database.name}}-service
  namespace: {{ .Values.org_charts.namespace }}
spec:
  type: {{ .Values.org_charts.database.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.org_charts.database.name }}-deployment
    app.kubernetes.io/part-of: {{ .Values.org_charts.name }}
  ports:
    - port: {{ .Values.org_charts.database.service.port }}
      targetPort: 3306

