global:
  repository_url: 'twister22'
  database_external: false

org_charts:
  name: org-charts
  namespace: 'org-charts'
  replicaCount: 1

  api:
    name: api
    image:
      url: 'organization-chart-api'
      tag: 'v1.0-SNAPSHOT'
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080

  database:
    enable: true
    name: mysql
    image:
      url: 'mysql'
      tag: '5.7'
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 3306
    credentials:
      hostname: 'mysql-service'
      username: twister
      password: '1653'
      root_pwd: '1994'
      database_name: 'organization_charts'
    pvc_mount_path: /var/lib/mysql

  pvc:
    enable: true
    name: mysql-pvc
    storage: '3Gi'

  serviceAccount:
    create: true
    annotations: {}
    name: 'org-charts-svc'

  podAnnotations: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"


  autoscaling:
    enabled: false
    name: autoscaler
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
